// @ts-check

/**
 * @typedef {object} TrackStatus
 * @property {string} [track]
 * @property {string} [artist]
 * @property {string} [source]
 * @property {string} [image]
 */

/** @param {unknown} value */
const text = (value) => String(value || '').trim();

const PROMO_MARKERS = [
  'official',
  'official\\s+(?:music\\s+)?video',
  'official\\s+audio',
  'music\\s+video',
  'video\\s+clip',
  'videoclipe',
  'vídeo\\s+oficial',
  'video\\s+oficial',
  'áudio\\s+oficial',
  'audio\\s+oficial',
  'clip\\s+officiel',
  'vid[ée]o\\s+officielle?',
  'audio\\s+officiel',
  'audio(?:\\s+only)?',
  'lyric(?:s|\\s+video)?',
  'letra',
  'con\\s+letra',
  'video\\s+con\\s+letra',
  'visuali[sz]er',
  'performance\\s+video',
  'pseudo\\s+video',
  'full\\s+video',
  'official\\s+m/?v',
  'm/?v',
  'amv',
  'hd',
  'hq',
  'uhd',
  '[48]k',
  '(?:720|1080|1440|2160)p',
  '\\d{2,3}fps',
  'explicit',
  'clean\\s+version',
  'premiere',
  'offizielles\\s+(?:musik)?video',
  'video\\s+ufficiale',
  'teledysk',
].join('|');

// no \b around CJK/Cyrillic: they are non-word chars in JS regex, so a boundary never matches
const WIDE_PROMO_MARKERS = [
  '公式(?:ミュージック)?(?:ビデオ|映像|音源|MV)?',
  'ミュージックビデオ',
  '歌詞(?:ビデオ|動画)?',
  '官方(?:MV|音[樂乐]?|[视視][频頻]|影片)?',
  '뮤직비디오',
  '공식(?:\\s*(?:영상|뮤직비디오|음원))?',
  '오피셜',
  '가사',
  'официальн(?:ый|ое)\\s+(?:клип|видео|аудио)',
].join('|');

const PROMO_ALT = `(?:\\b(?:${PROMO_MARKERS})\\b|(?:${WIDE_PROMO_MARKERS}))`;
const PROMO_TAG = new RegExp(PROMO_ALT, 'i');
const PROMO_SUFFIX = new RegExp(`\\s*[\\[(][^)\\]]*${PROMO_ALT}[^)\\]]*[\\])]\\s*$`, 'i');
const LOOSE_PROMO_SUFFIX = new RegExp(`\\s*(?:[-–—|•]\\s*)+${PROMO_ALT}\\s*$`, 'i');
const LIVE_VIDEO_SUFFIX = /\s*[\[(](?:official\s+)?live\s+(?:music\s+)?video[\])]\s*$/i;
// Album rips number their tracks: "Technologic #02". Two digits only, so a song called "#1" survives.
const TRACK_INDEX_SUFFIX = /\s*#\d{2,3}\s*$/;
const ARTIST_CHANNEL_SUFFIX = /\s*(?:[-–—|•]\s*)?(?:Topic|Official Artist Channel|Auto-generated by YouTube)$/i;

// "Song - Artist" is as common as "Artist - Song", so the channel name breaks the tie when it matches a side
const channelName = (/** @type {string} */ value) => value.replace(ARTIST_CHANNEL_SUFFIX, '').replace(/VEVO$/i, '').trim();
const stripPromo = (/** @type {string} */ value) => value.replace(PROMO_SUFFIX, '').replace(LOOSE_PROMO_SUFFIX, '').trim();
const nameKey = (/** @type {string} */ value) => stripPromo(value).toLowerCase().replace(/[^\p{L}\p{N}]/gu, '');

/** @param {TrackStatus} status */
function trackMetadata(status) {
  let artist = text(status.artist);
  let title = text(status.track);
  const source = text(status.source).toLowerCase();
  const isYouTube = source.includes('youtube') || /ytimg\.com/i.test(text(status.image));
  const split = title.match(/^(.{1,80}?)\s+[–—-]\s+(.+)$/);
  // the channel didn't say which side is the artist; the caller settles it against the album-art lookup
  let ambiguous = false;

  if (split && isYouTube) {
    const channel = nameKey(channelName(artist));
    const matches = channel ? [channel === nameKey(split[1]), channel === nameKey(split[2])] : [false, false];
    const reversed = matches[1] && !matches[0];
    ambiguous = !matches[0] && !matches[1];
    artist = stripPromo(reversed ? split[2] : split[1]);
    title = (reversed ? split[1] : split[2]).trim();
  } else if (isYouTube && PROMO_TAG.test(artist) && !PROMO_TAG.test(title)) {
    [artist, title] = [title, artist];
  } else if (artist && title) {
    const escaped = artist.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    title = title.replace(new RegExp(`^${escaped}\\s*[–—:-]\\s*`, 'i'), '').trim() || title;
  }

  title = title.replace(LIVE_VIDEO_SUFFIX, ' (Live)').trim();
  let cleaned;
  do {
    cleaned = title
      .replace(PROMO_SUFFIX, '')
      .replace(LOOSE_PROMO_SUFFIX, '')
      .replace(TRACK_INDEX_SUFFIX, '')
      .trim();
    if (cleaned === title) break;
    title = cleaned;
  } while (title);

  artist = artist
    .replace(ARTIST_CHANNEL_SUFFIX, '')
    .replace(/VEVO$/i, '')
    .trim();

  return { artist, title, ambiguous };
}

module.exports = { trackMetadata };