// @ts-check

/**
 * @typedef {object} TrackStatus
 * @property {string} [track]
 * @property {string} [artist]
 * @property {string} [source]
 * @property {string} [image]
 */

/** @param {unknown} value */
const text = (value) => String(value || '').trim();

const PROMO_MARKERS = [
  'official',
  'official\\s+(?:music\\s+)?video',
  'official\\s+audio',
  'music\\s+video',
  'video\\s+clip',
  'videoclipe',
  'vídeo\\s+oficial',
  'video\\s+oficial',
  'áudio\\s+oficial',
  'audio\\s+oficial',
  'audio(?:\\s+only)?',
  'lyric(?:s|\\s+video)?',
  'letra',
  'con\\s+letra',
  'video\\s+con\\s+letra',
  'visuali[sz]er',
  'performance\\s+video',
  'pseudo\\s+video',
  'full\\s+video',
  'official\\s+m/?v',
  'm/?v',
  'amv',
  'hd',
  'hq',
  'uhd',
  '[48]k',
  '(?:720|1080|1440|2160)p',
  '\\d{2,3}fps',
  'explicit',
  'clean\\s+version',
  'premiere',
].join('|');

const PROMO_TAG = new RegExp(`\\b(?:${PROMO_MARKERS})\\b`, 'i');
const PROMO_SUFFIX = new RegExp(`\\s*[\\[(][^)\\]]*\\b(?:${PROMO_MARKERS})\\b[^)\\]]*[\\])]\\s*$`, 'i');
const LOOSE_PROMO_SUFFIX = new RegExp(`\\s*(?:[-–—|•]\\s*)+(?:${PROMO_MARKERS})\\s*$`, 'i');
const LIVE_VIDEO_SUFFIX = /\s*[\[(](?:official\s+)?live\s+(?:music\s+)?video[\])]\s*$/i;
const ARTIST_CHANNEL_SUFFIX = /\s*(?:[-–—|•]\s*)?(?:Topic|Official Artist Channel|Auto-generated by YouTube)$/i;

/** @param {TrackStatus} status */
function trackMetadata(status) {
  let artist = text(status.artist);
  let title = text(status.track);
  const source = text(status.source).toLowerCase();
  const isYouTube = source.includes('youtube') || /ytimg\.com/i.test(text(status.image));
  const split = title.match(/^(.{1,80}?)\s+[–—-]\s+(.+)$/);

  if (split && isYouTube) {
    artist = split[1].trim();
    title = split[2].trim();
  } else if (isYouTube && PROMO_TAG.test(artist) && !PROMO_TAG.test(title)) {
    [artist, title] = [title, artist];
  } else if (artist && title) {
    const escaped = artist.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    title = title.replace(new RegExp(`^${escaped}\\s*[–—:-]\\s*`, 'i'), '').trim() || title;
  }

  title = title.replace(LIVE_VIDEO_SUFFIX, ' (Live)').trim();
  let cleaned;
  do {
    cleaned = title
      .replace(PROMO_SUFFIX, '')
      .replace(LOOSE_PROMO_SUFFIX, '')
      .trim();
    if (cleaned === title) break;
    title = cleaned;
  } while (title);

  artist = artist
    .replace(ARTIST_CHANNEL_SUFFIX, '')
    .replace(/VEVO$/i, '')
    .trim();

  return { artist, title };
}

module.exports = { trackMetadata };